SELECT ?person ?personLabel ?year


WHERE {

  ?person wdt:P463 wd:Q270794;

          p:P463 [pq:P580 ?year].

  ?person wdt:P21 wd:Q6581072;

          p:P69 [ps:P69 wd:Q49112; pq:P512 wd:Q752297]

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
