SELECT ?person ?personLabel ?schoolLabel 


WHERE {

  ?person wdt:P463 wd:Q270794.

  ?person wdt:P21 wd:Q6581072;

          p:P69 [ps:P69 ?school; pq:P512 wd:Q752297]

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
