SELECT ?person ?personLabel ?year


WHERE {

  ?person wdt:P21 wd:Q6581072.

  ?person wdt:P463 wd:Q270794;

          p:P463 [ps:P463 wd:Q270794; pq:P580 ?year].


  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
