SELECT DISTINCT ?person ?personLabel ?year ?occLabel


WHERE {

  

  ?person wdt:P21 wd:Q6581072.

  ?person wdt:P106 ?occ.

  ?person wdt:P69 wd:Q49112;

          p:P69 [pq:P512 wd:Q752297];

          p:P69 [pq:P582 ?year].

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
  FILTER(YEAR(?year) < 1969).

}
